apiVersion: v2
name: open-source-stack-for-startups
version: 1.0.0

dependencies:
- name: keycloak
  version: 18.4.0
  repository: https://charts.bitnami.com/bitnami
- name: contour
  version: 15.5.2
  repository: https://charts.bitnami.com/bitnami
- name: cert-manager
  version: 1.14.3
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
- name: postgresql
  version: 13.4.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: mariadb
  condition: mariadb.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 11.5.7
- name: prometheus
  version: 25.13.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
- name: grafana
  version: 7.3.0
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
- name: loki
  version: 5.43.6
  repository: https://grafana.github.io/helm-charts
  condition: loki.enabled
- name: promtail
  version: 6.15.5
  repository: https://grafana.github.io/helm-charts
  condition: promtail.enabled
- name: kimai2
  version: 3.1.11
  repository: https://robjuz.github.io/helm-charts
  condition: kimai2.enabled
- name: openproject
  version: 4.5.0
  repository: https://charts.openproject.org
  condition: openproject.enabled
- name: wiki
  version: 2.2.0
  repository: https://charts.js.wiki
  condition: wiki.enabled
- name: planka
  version: 0.1.17
  repository: file://./planka
  condition: planka.enabled
- name: plane-ce
  repository: https://helm.plane.so
  version: 1.0.11
  condition: plane-ce.enabled
