###############################################################
# BASE VARIABLES
###############################################################
global:
  domain: localhost

###############################################################
# NETWORK
###############################################################
cert-manager:
  enabled: false

ingress-nginx:
  controller:
    metrics:
      enabled: true

      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"

###############################################################
# DATABASES
###############################################################
# Deploy postgres DB if no external DB is set
postgresql:
  enabled: true
  architecture: standalone

  # Override defaults values for the DB
  # TODO: use secrets for DB credentials
  auth:
    database: keycloak
    existingSecret: osss-psql-secrets
    keys:
      username: username
      postgres-password: password

  metrics:
    enabled: true

  primary:
    initdb:
      scriptsConfigMap: "{{ .Release.Name }}-postgres-init"

mariadb:
  enabled: true
  architecture: standalone

  metrics:
    enabled: true

  # TODO: use secrets for DB credentials
  auth:
    database: kimai
    existingSecret: osss-mariadb-secrets
    keys:
      username: username
      password: password
      rootPassword: rootPassword

  primary:
    persistence:
      enabled: true
      storageClass:
      accessModes:
        - ReadWriteOnce
      size: 4Gi

###############################################################
# IDP
###############################################################
keycloak:
  production: true
  proxy: edge

  # Disable local postgres
  postgresql:
    enabled: false

  # Root user configuration
  # TODO: use secrets for root user credentials
  auth:
    adminUser: admin
    adminPassword: admin
    # existingSecret: osss-keycloak-secret-user-credentials
    # passwordSecretKey: admin-password

  # Create preconfigured realm
  keycloakConfigCli:
    enabled: true
    existingConfigmap: "{{ .Release.Name }}-keycloak-realm"
    backoffLimit: 5

    cleanupAfterFinished:
      enabled: true
      seconds: 600

  # Use external DB
  # TODO: use secrets for DB credentials
  externalDatabase:
    host: "{{ .Release.Name }}-postgresql"
    database: keycloak
    user: testuser
    password: testpassword

  # Enable prometheus metrics endpoint
  metrics:
    enabled: true

###############################################################
# MONITORING
###############################################################
prometheus:
  enabled: true

  # Disable pushgateway
  prometheus-pushgateway:
    enabled: false

  # Disable alertmanager
  alertmanager:
    enabled: false

promtail:
  enabled: true

  config:
    clients:
      - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push

loki:
  enabled: true

  test:
    enabled: false

  gateway:
    enabled: false

  monitoring:
    dashboards:
      enabled: false

    lokiCanary:
      enabled: false

    selfMonitoring:
      enabled: false

      serviceMonitor:
        enabled: false

      grafanaAgent:
        installOperator: false

  loki:
    auth_enabled: false

    commonConfig:
      replication_factor: 1

    storage:
      type: filesystem

  singleBinary:
    replicas: 1

grafana:
  enabled: true
  assertNoLeakedSecrets: false

  # TODO: use secret for root user
  adminUser: admin
  adminPassword: admin

  # Enable hot reload of dashboards and datasources
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

  # Configure SSO with keycloak
  grafana.ini:
    server:
      root_url: "http://grafana.{{ .Values.global.domain }}"

    dashboards:
      default_home_dashboard_path: /tmp/dashboards/dashboard_main.json

    # TODO: use secrets for sensible parameters
    auth.generic_oauth:
      enabled: true
      name: keycloak
      allow_sign_up: true
      client_id: grafana
      client_secret: nuWbw2dO8KAiU8ZMEO5KzQWqbt42dZyW
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      auth_url: "http://keycloak.{{ .Values.global.domain }}/realms/osss/protocol/openid-connect/auth"
      token_url: http://osss-keycloak/realms/osss/protocol/openid-connect/token
      api_url: http://osss-keycloak/realms/osss/protocol/openid-connect/userinfo
      role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'

###############################################################
# TOOLS
###############################################################
kimai2:
  enabled: false

  # TODO: use secret for root user
  kimaiAdminEmail: admin@example.com
  kimaiAdminPassword: adminadmin

  service:
    type: ClusterIP

  ingress:
    hostname: kimai.test.local

  configurationFromSecret:
    enabled: true

  mariadb:
    enabled: false

  # TODO: use secrets for DB credentials
  externalDatabase:
    host: osss-mariadb
    port: 3306
    user: kimai
    password: kimai
    database: kimai

openproject:
  enabled: false

  # Override hostname
  host: openproject.localhost

  # Root user configuration
  # TODO: use secret for root user
  admin_user:
    password: admin
    password_reset: false
    name: admin

  # SSO with keycloak
  # TODO: research if can be implemented in free version
  oidc:
    enabled: true
    provider: Keycloak
    displayName: Keycloak
    host: keycloak.localhost
    identifier: http://openprojects.localhost
    secret: asd
    issuer: http://keycloak.localhost/realms/osss
    authorizationEndpoint: /realms/osss/protocol/openid-connect/auth
    tokenEndpoint: /realms/osss/protocol/openid-connect/token
    userinfoEndpoint: /realms/osss/protocol/openid-connect/userinfo
    endSessionEndpoint: http://keycloak.localhost/realms/osss/protocol/openid-connect/logout

  # Limit cpu to work in minikube
  # TODO: parametrize and use default for minikube
  resources:
    limits:
      cpu: 1

  # Disable https (manage at ingress level)
  openproject:
    https: false

  # Use common postgresql
  postgresql:
    bundled: false

    # TODO: parametrize values
    connection:
      host: osss-postgresql
      port: 5432

    # TODO: use secrets for DB credentials
    auth:
      database: openproject
      username: testuser
      password: testpassword

  # Disable ingress
  ingress:
    enabled: false

wiki:
  enabled: false

  ingress:
    enabled: false

  postgresql:
    enabled: false

    # TODO: use secrets for DB credentials
    postgresqlHost: osss-postgresql
    postgresqlDatabase: wiki
    postgresqlUser: testuser
    existingSecret: osss-db
    existingSecretKey: password

planka:
  enabled: false

  admin_email: admin
  admin_password: admin
  admin_username: admin
  admin_name: admin

  baseUrl: "http://planka.{{ .Values.global.domain }}"
  secretkey: 4dab9dc2d9011d9114b9a96e531926598adad75c70b41e78311bf96097d327812c191091852b9a7ed90e56058b4ee52ba2398ba54398f7bc9c7827785cc3a342

  # TODO: set db hostname
  postgresql:
    enabled: false

    # TODO: use secrets for DB credentials
    auth:
      database: planka
      username: testuser
      password: testpassword

  # Do not enable unless a real domain is being used
  oidc:
    enabled: false

    clientId: planka
    clientSecret: nuWbw2dO8KAiU8ZMEO5KzQWqbt42dZy2
    issuerUrl: http://keycloak.{{ .Values.global.domain }}/realms/osss

# TODO: configure plane-ce
plane-ce:
  enabled: false

odoo:
  enabled: true

  service:
    type: ClusterIP

  customPostInitScripts:

    01_git-installation.sh: |
      #!/bin/bash
      apt-get update && apt-get install -y git

    03_python-jose-installation.sh: |
      #!/bin/bash

      # Change to the Odoo directory
      cd ../opt/bitnami/odoo/ || { echo "Directory not found"; exit 1; }

      # Activate the virtual environment
      source venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }

      # Install the required Python package
      pip3 install python-jose || { echo "Failed to install python-jose"; exit 1; }

    02_auth-module-repo-download.sh: |
      #!/bin/bash

      cd ../opt/bitnami/odoo/addons || { echo "Directory not found"; exit 1; }
      git clone --branch 17.0 --single-branch "https://github.com/OCA/server-auth.git"

    04_auth-oidc-fix.sh: |
      #!/bin/bash
      cd ../opt/bitnami/odoo/addons/server-auth
      mv auth_oidc ..
      cd ..
      rm -rf ./server-auth

    

  postgresql:
    enabled: false

  # TODO: parametrize and use secrets
  externalDatabase:
    host: osss-postgresql
    port: 5432
    user: testuser
    database: odoo
    create: false
    password: testpassword
    postgresqlPostgresPassword: testpassword
    postgresqlPostgresUser: testuser
