domain: localhost

# Deploy postgres DB if no external DB is set
postgresql:
  enabled: true
  architecture: standalone

  # Override defaults values for the DB
  auth:
    username: testuser
    password: testpassword
    database: keycloak

  metrics:
    enabled: true

  primary:
    initdb:
      scripts:
        create_dbs.sql: |
          CREATE DATABASE openproject;

# IDP
keycloak:
  # Disable local postgres
  postgresql:
    enabled: false

  # Create preconfigured realm
  keycloakConfigCli:
    enabled: true
    existingConfigmap: "{{ .Release.Name }}-keycloak-realm"
    backoffLimit: 5

    cleanupAfterFinished:
      enabled: true
      seconds: 600

  # Use external DB
  externalDatabase:
    host: "{{ .Release.Name }}-postgresql"
    database: keycloak
    user: testuser
    password: testpassword

  # Enable prometheus metrics endpoint
  metrics:
    enabled: true

# MONITORING
prometheus:
  enabled: true

  prometheus-pushgateway:
    enabled: false

  alertmanager:
    enabled: false

grafana:
  enabled: true

  # Enable hot reload of dashboards and datasources
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

  # Configure SSO with keycloak
  grafana.ini:
    server:
      # root_url: grafana.localhost

      auth.generic_oauth:
        enabled: true
        name: Keycloak-OAuth
        allow_sign_up: true
        client_id: grafana-oauth
        client_secret: nuWbw2dO8KAiU8ZMEO5KzQWqbt42dZyW
        scopes: openid email profile offline_access roles
        email_attribute_path: email
        login_attribute_path: username
        name_attribute_path: full_name
        auth_url: https://keycloak.localhost/realms/osss/protocol/openid-connect/auth
        token_url: https://keycloak.localhost/realms/osss/protocol/openid-connect/token
        api_url: https://keycloak.localhost/realms/osss/protocol/openid-connect/userinfo
        role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'

# TOOLS
kimai2:
  enabled: false

  kimaiAdminEmail: admin
  kimaiAdminPassword: test1

openproject:
  enabled: true

  # Use common postgresql
  postgresql:
    bundled: false

    connection:
      host: osss-postgresql
      port: 5432

    auth:
      database: openproject
      username: testuser
      password: testpassword

  # Disable ingress
  ingress:
    enabled: false
