###############################################################
# BASE VARIABLES
###############################################################
domain: localhost

###############################################################
# NETWORK
###############################################################
cert-manager:
  enabled: false

###############################################################
# DATABASES
###############################################################
# Deploy postgres DB if no external DB is set
postgresql:
  enabled: true
  architecture: standalone

  # Override defaults values for the DB
  auth:
    username: testuser
    password: testpassword
    database: keycloak

  metrics:
    enabled: true

  primary:
    initdb:
      scripts:
        00_create_dbs.sql: |
          CREATE DATABASE planka;
          CREATE DATABASE wiki;
          CREATE DATABASE openproject;

mariadb:
  enabled: true
  architecture: standalone

  metrics:
    enabled: true

  auth:
    rootPassword: kimaiR00tPassw0rd
    database: kimai
    username: kimai
    password: kimai

  primary:
    persistence:
      enabled: true
      storageClass:
      accessModes:
        - ReadWriteOnce
      size: 4Gi

###############################################################
# IDP
###############################################################
keycloak:
  # Disable local postgres
  postgresql:
    enabled: false

  # Root user configuration
  auth:
    adminUser: admin
    adminPassword: admin

  # Create preconfigured realm
  keycloakConfigCli:
    enabled: true
    existingConfigmap: "{{ .Release.Name }}-keycloak-realm"
    backoffLimit: 5

    cleanupAfterFinished:
      enabled: true
      seconds: 600

  # Use external DB
  externalDatabase:
    host: "{{ .Release.Name }}-postgresql"
    database: keycloak
    user: testuser
    password: testpassword

  # Enable prometheus metrics endpoint
  metrics:
    enabled: true

###############################################################
# MONITORING
###############################################################
prometheus:
  enabled: true

  # Disable pushgateway
  prometheus-pushgateway:
    enabled: false

  # Disable alertmanager
  alertmanager:
    enabled: false

promtail:
  enabled: true

  config:
    clients:
      - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push

loki:
  enabled: true

  test:
    enabled: false

  gateway:
    enabled: false

  monitoring:
    lokiCanary:
      enabled: false

    selfMonitoring:
      enabled: false

      serviceMonitor:
        enabled: false

      grafanaAgent:
        installOperator: false

  loki:
    auth_enabled: false

    commonConfig:
      replication_factor: 1

    storage:
      type: filesystem

  singleBinary:
    replicas: 1

grafana:
  enabled: true
  assertNoLeakedSecrets: false

  adminUser: admin
  adminPassword: admin

  # Enable hot reload of dashboards and datasources
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

  # Configure SSO with keycloak
  grafana.ini:
    server:
      root_url: http://grafana.localhost

    # dashboards:
    #   default_home_dashboard_path:

    auth.generic_oauth:
      enabled: true
      name: keycloak
      allow_sign_up: true
      client_id: grafana
      client_secret: nuWbw2dO8KAiU8ZMEO5KzQWqbt42dZyW
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      auth_url: http://keycloak.localhost/realms/osss/protocol/openid-connect/auth
      token_url: http://osss-keycloak/realms/osss/protocol/openid-connect/token
      api_url: http://osss-keycloak/realms/osss/protocol/openid-connect/userinfo
      role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'

###############################################################
# TOOLS
###############################################################
kimai2:
  enabled: false

  kimaiAdminEmail: admin
  kimaiAdminPassword: admin

  configurationFromSecret:
    enabled: true

  mariadb:
    enabled: false

  externalDatabase:
    host: osss-mariadb
    port: 3306
    user: kimai
    password: kimai
    database: kimai

openproject:
  enabled: false

  # Override hostname
  host: openproject.localhost

  # Root user configuration
  admin_user:
    password: admin
    password_reset: false
    name: admin

  # SSO with keycloak
  oidc:
    enabled: true
    provider: Keycloak
    displayName: Keycloak
    host: keycloak.localhost
    identifier: http://openprojects.localhost
    secret: asd
    issuer: http://keycloak.localhost/realms/osss
    authorizationEndpoint: /realms/osss/protocol/openid-connect/auth
    tokenEndpoint: /realms/osss/protocol/openid-connect/token
    userinfoEndpoint: /realms/osss/protocol/openid-connect/userinfo
    endSessionEndpoint: http://keycloak.localhost/realms/osss/protocol/openid-connect/logout

  # Limit cpu to work in minikube
  resources:
    limits:
      cpu: 1

  # Disable https (manage at ingress level)
  openproject:
    https: false

  # Use common postgresql
  postgresql:
    bundled: false

    connection:
      host: osss-postgresql
      port: 5432

    auth:
      database: openproject
      username: testuser
      password: testpassword

  # Disable ingress
  ingress:
    enabled: false

wiki:
  enabled: false

  ingress:
    enabled: false

  postgresql:
    enabled: false

    postgresqlHost: osss-postgresql
    postgresqlDatabase: wiki
    postgresqlUser: testuser
    existingSecret: osss-db
    existingSecretKey: password

planka:
  enabled: true

  admin_email: admin
  admin_password: admin
  admin_username: admin
  admin_name: admin

  baseUrl: http://planka.localhost
  secretkey: 4dab9dc2d9011d9114b9a96e531926598adad75c70b41e78311bf96097d327812c191091852b9a7ed90e56058b4ee52ba2398ba54398f7bc9c7827785cc3a342

  postgresql:
    enabled: false

    auth:
      database: planka
      username: testuser
      password: testpassword

  oidc:
    enabled: false

    clientId: planka
    clientSecret: nuWbw2dO8KAiU8ZMEO5KzQWqbt42dZy2
    issuerUrl: http://osss-keycloak/realms/osss
