{
 "title": "Keycloak Metrics Dashboard",
 "description": "Dashboard of Keycloak metrics exported with Keycloak Metrics SPI\r\n\r\nhttps://github.com/aerogear/keycloak-metrics-spi",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(keycloak_logins,kubernetes_pod_name)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins{provider=\"keycloak\"},realm)"
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": "label_values(keycloak_logins{provider=\"keycloak\",realm=\"$realm\"},client_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_pod_name=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{kubernetes_pod_name=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_pod_name=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{kubernetes_pod_name=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{kubernetes_pod_name=\"$instance\"})",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}