apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xbuiltinobjects.keycloak.crossplane.io
spec:
  group: keycloak.crossplane.io
  names:
    categories:
    - composite
    kind: XBuiltinObjects
    listKind: XBuiltinObjectsList
    plural: xbuiltinobjects
    singular: xbuiltinobjects
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .spec.compositionRef.name
      name: COMPOSITION
      type: string
    - jsonPath: .spec.compositionRevisionRef.name
      name: COMPOSITIONREVISION
      priority: 1
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                type: string
            type: object
          spec:
            properties:
              builtinAuthenticationFlows:
                description: List of authentication flows to import from the realm
                items:
                  type: string
                type: array
              builtinClients:
                description: List of clients to import from the realm
                items:
                  type: string
                type: array
              builtinRealmRoles:
                description: List of realm roles to import from the realm
                items:
                  enum:
                  - offline_access
                  - uma_authorization
                  - admin
                  - create-realm
                  - default-roles-master
                  type: string
                type: array
              claimRef:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - apiVersion
                - kind
                - namespace
                - name
                type: object
              compositionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionRevisionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionRevisionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              compositionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              compositionUpdatePolicy:
                default: Automatic
                enum:
                - Automatic
                - Manual
                type: string
              providerConfigName:
                description: Name of the provider config to attach to the imported
                  clients/roles
                type: string
              providerSecretName:
                description: Name of the secret containing the provider credentials
                  (Secret must have a label with key=type and value=provider-credentials
                  to be found)
                type: string
              realm:
                description: Realm to import the builtin clients/roles from
                type: string
              resourceRefs:
                items:
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                  - apiVersion
                  - kind
                  type: object
                type: array
                x-kubernetes-list-type: atomic
              writeConnectionSecretToRef:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                type: object
            required:
            - providerConfigName
            - providerSecretName
            - realm
            type: object
          status:
            properties:
              claimConditionTypes:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: set
              conditions:
                description: Conditions of the resource.
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              connectionDetails:
                properties:
                  lastPublishedTime:
                    format: date-time
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
