{{- if index .Values "cert-manager" "enabled" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-pk
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
{{- end }}
