apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: keycloak-db-secret

data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
