# https://gitlab.com/corewire/images/crossplane/function-keycloak-builtin-objects
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuiltinobjects.keycloak.crossplane.io
spec:
  group: keycloak.crossplane.io
  names:
    kind: XBuiltinObjects
    plural: xbuiltinobjects
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              realm:
                type: string
                description: Realm to import the builtin clients/roles from
              builtinClients:
                type: array
                items:
                  type: string
                description: List of clients to import from the realm 
              builtinRealmRoles:
                type: array
                items:
                  type: string
                  enum:
                    - offline_access
                    - uma_authorization
                    - admin
                    - create-realm
                    - default-roles-master
                description: List of realm roles to import from the realm
              builtinAuthenticationFlows:
                type: array
                items:
                  type: string
                description: List of authentication flows to import from the realm
              providerConfigName:
                type: string
                description: Name of the provider config to attach to the imported clients/roles
              providerSecretName:
                type: string
                description: Name of the secret containing the provider credentials (Secret must have a label with key=type and value=provider-credentials to be found)
            required:
            - providerConfigName
            - providerSecretName
            - realm
        required:
        - spec
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: keycloak-builtin-objects
spec:
  compositeTypeRef:
    apiVersion: keycloak.crossplane.io/v1alpha1
    kind: XBuiltinObjects
  mode: Pipeline
  pipeline:
  - step: pull-provider-configs
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
          - kind: Secret
            into: secrets
            apiVersion: v1
            type: Selector 
            selector:
              minMatch: 1
              maxMatch: 100
              matchLabels:
                - key: type
                  type: Value
                  value: provider-credentials
          - kind: Role
            into: roles
            apiVersion: role.keycloak.crossplane.io/v1alpha1
            type: Selector
            selector:
              minMatch: 0
              maxMatch: 20
              matchLabels:
                - key: type
                  type: Value
                  value: modifiedrole
  - step: keycloak-builtin-objects
    functionRef:
      name: function-keycloak-builtin-objects
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-extra-resources
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-extra-resources:v0.0.3
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.4.2
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-keycloak-builtin-objects
spec:
  package: registry.gitlab.com/corewire/images/crossplane/function-keycloak-builtin-objects:v3.0.0
  packagePullPolicy: Always
---
# Sync all precreated resources from master realm
apiVersion: keycloak.crossplane.io/v1alpha1
kind: XBuiltinObjects
metadata:
  name: keycloak-builtin-objects-master
spec:
  providerConfigName: keycloak-provider-config
  providerSecretName: keycloak-credentials
  realm: master
  builtinClients: 
    - account
    - account-console
    - admin-cli
    - broker
    - master-realm
    - security-admin-console
  builtinRealmRoles:
    - offline_access
    - uma_authorization
    - admin
    - default-roles-master
    - create-realm
  builtinAuthenticationFlows:
    - browser
