apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-dashboards
  labels:
    grafana_dashboard: "true"
data: # TODO: make this iterate over json in grafana folder
  dashboard_postgres.json: |
{{ .Files.Get "grafana/dashboard_postgresql.json" | indent 4 }}
  dashboard_mysql.json: |
{{ .Files.Get "grafana/dashboard_mysql.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    grafana_datasource: "true"
data:
  prometheus.yml: |-
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        url: http://{{ .Release.Name }}-prometheus-server
      - name: loki
        type: loki
        url: http://{{ .Release.Name }}-loki:3100
