apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-dashboards
  labels:
    grafana_dashboard: "true"
data:
  dashboard_postgres.json: |
{{ .Files.Get "grafana/dashboard_postgresql.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    grafana_datasource: "true"
data:
  prometheus.yml: |-
    apiVersion: 1
    datasources:
      - name: prometheus-osss
        type: prometheus
        url: http://{{ .Release.Name }}-prometheus-server
