apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-postgres
  labels:
    grafana_dashboard: "true"
data:
  dashboard_postgres.json: |
{{ .Files.Get "grafana/dashboard_postgresql.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus
  labels:
    grafana_datasource: "true"
data:
  prometheus.yml: |-
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        url: http://test-prometheus-server
