apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osss-ingress-main
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://keycloak.{{ .Values.global.domain }}/realms/master/account
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-keycloak
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osss-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    {{- if index .Values "cert-manager" "enabled" }}
    cert-manager.io/cluster-issuer: "letsencrypt"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if index .Values "cert-manager" "enabled" }}
  tls:
  {{- if .Values.openproject.enabled }}
  - secretName: {{ .Release.Name }}-tls-openproject
    hosts:
    - "openproject.{{ .Values.global.domain }}"
  {{- end }}
  {{- if .Values.kimai2.enabled }}
  - secretName: {{ .Release.Name }}-tls-kimai
    hosts:
    - "kimai.{{ .Values.global.domain }}"
  {{- end }}
  {{- if .Values.wiki.enabled }}
  - secretName: {{ .Release.Name }}-tls-wiki
    hosts:
    - "wiki.{{ .Values.global.domain }}"
  {{- end }}
  {{- if .Values.planka.enabled }}
  - secretName: {{ .Release.Name }}-tls-planka
    hosts:
    - "planka.{{ .Values.global.domain }}"
  {{- end }}
  {{- if .Values.odoo.enabled }}
  - secretName: {{ .Release.Name }}-tls-odoo
    hosts:
    - "odoo.{{ .Values.global.domain }}"
  {{- end }}
  {{- end }}
  rules:
    {{- if .Values.openproject.enabled }}
    - host: openproject.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-openproject
                port:
                  number: 8080
    {{- end }}
    {{- if .Values.kimai2.enabled }}
    - host: kimai.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-kimai2
                port:
                  number: 80
    {{- end }}
    {{- if .Values.wiki.enabled }}
    - host: wiki.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-wiki
                port:
                  number: 80
    {{- end }}
    {{- if .Values.planka.enabled }}
    - host: planka.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-planka
                port:
                  number: 1337
    {{- end }}
    {{- if .Values.odoo.enabled }}
    - host: odoo.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-odoo
                port:
                  number: 80
    {{- end }}
