# Siguiendo con la misma lógica, se utiliza en values keycloakConfigCli
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.keycloak.keycloakConfigCli.existingConfigmap . }}
data:
  realm.yml: {{ include "realm.yml" . | toJson }}
