---
# Acaso estos secrets estan siendo usados?
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ .Release.Name }}-db

data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
---
{{- if .Values.planka.enabled }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: planka-postgresql-svcbind-custom-user

data:
  uri: {{ "postgresql://testuser:testpassword@osss-postgresql:5432/planka" | b64enc }}
---
# Específico del chart de postgres de bitnami. Este permite mediante primary.initdb.scriptsConfigMap especificar el recurso de ConfigMap
# para utilizar. En este caso, se utiliza para crear más databases, ya que desde el chart se puede especificar solo una
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-init
data:
  init.sql: |
    CREATE DATABASE planka;
    CREATE DATABASE wiki;
    CREATE DATABASE openproject;
    CREATE DATABASE odoo;
