---
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ .Release.Name }}-db

data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
---
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: planka-postgresql-svcbind-custom-user

data:
  uri: {{ "postgresql://testuser:testpassword@osss-postgresql:5432/planka" | b64enc }}
