---
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ .Release.Name }}-db

data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
---
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: planka-postgresql-svcbind-custom-user

data:
  uri: {{ "postgresql://testuser:testpassword@osss-postgresql:5432/planka" | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-init
data:
  init.sql: |
{{- if .Values.planka.enabled }}
    CREATE DATABASE planka;
{{- end }}
{{- if .Values.wiki.enabled }}
    CREATE DATABASE wiki;
{{- end }}
{{- if .Values.openproject.enabled }}
    CREATE DATABASE openproject;
{{- end }}
